apiVersion: v1
kind: Service
metadata:
  name: m324-team6-m324-team6@
  namespace: m324-team6
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: m324-team6-m324-team6@
